### ISSUE TITLE
Some datasets missing one time stamp compared to the UCR

### ISSUE THREAD

**Issue by hadifawaz1999** [ML4ITS/TimeVQVAE#1]
Hello,

First thank you very much for the simplicity of reproducing your work, the notebook is very straightforward, and I really enjoyed reading your work.

While reproducing the generation for all the datasets using the notebook and the pre-trained models you provide, I noticed that for 33 datasets the generations have 1 time stamp less than the original dataset. The generations are correct though I plotted them and they have the right form but when i print the shape they have one time stamp less. Here is the list of the datasets:

['ArrowHead',
 'Car',
 'CinCECGTorso',
 'DiatomSizeReduction',
 'EthanolLevel',
 'FaceAll',
 'FacesUCR',
 'Fish',
 'FreezerRegularTrain',
 'FreezerSmallTrain',
 'Fungi',
 'GesturePebbleZ1',
 'GesturePebbleZ2',
 'Ham',
 'HandOutlines',
 'InsectEPGRegularTrain',
 'InsectEPGSmallTrain',
 'Lightning2',
 'Lightning7',
 'MedicalImages',
 'OSULeaf',
 'PickupGestureWiimoteZ',
 'ShakeGestureWiimoteZ',
 'SmoothSubspace',
 'SonyAIBORobotSurface2',
 'Strawberry',
 'ToeSegmentation1',
 'ToeSegmentation2',
 'Trace',
 'UWaveGestureLibraryAll',
 'UWaveGestureLibraryX',
 'UWaveGestureLibraryY',
 'UWaveGestureLibraryZ']

Can you let me know if:

1- This is my wrong doing or do you have the same thing when producing them yourselves.
2- If you do notice the same thing, do you know the reason your model does that ?

Thank you for your response in advance.

**Comment by danelee2601** [comment]
Hi! Thanks for your interest. The one timestep missing problem occurs due to the STFT (short-time Fourier transform) process.
Let's say we have time series `x` with a length of 101, then after it undergoes STFT and ISTFT, its length would become 100 instead of 101 (maybe not exactly 101 -> 100, but the problem is certainly due to the STFT operation).
