### ISSUE TITLE
Problem running this on multiple GPUs

### ISSUE THREAD

**Issue by Ofplarsen** [ML4ITS/TimeVQVAE#12]
Trouble when running this code on a cluster of GPUs

https://github.com/Lightning-AI/torchmetrics/issues/2477

**Comment by danelee2601** [comment]
The current code doesn't support the multiple gpu yet. But I'm planning to do update it.

**Comment by danelee2601** [comment]
Thanks for the feedback.

**Comment by Ofplarsen** [comment]
No problem, I'll manage with a single. Nice repo btw!

**Comment by Frndznz** [comment]
What would be the steps required to do this? @danelee2601 I have quite a large dataset and need to train on multiple GPUs

**Comment by danelee2601** [comment]
Hi @Frndznz. This repo hasn't bee developed to train on a very large dataset that can't be fit into CPU memory, as it was developed for a research purpose. But I'm sure you can modify the data pipeline to enable it. For instance, save a csv file that contains a list of all the available data file names and import the files for every iteration.
