### ISSUE TITLE
how to use timeVQVAE to generate a 1d singals?

### ISSUE THREAD

**Issue by jmren168** [ML4ITS/TimeVQVAE#13]
Thanks for the work.

I would like to use the proposed model to generate 1d signals, and then feed these singals to another CNN-like classification model.

How could I do to generate 1d singals using the model?

Any guides are highly appreciated.

**Comment by jmren168** [comment]
Yes, 1d signals mean univariate time series data.

**Comment by danelee2601** [comment]
Then it should be rather straightforward. Please refer to the README section, "Train it on a Custom Dataset".

**Comment by jmren168** [comment]
Thanks for the guide. I will try it.
