### ISSUE TITLE
Question? How do u conduct class-conditional generation? In the training stage, u don't have added any class prior information. 

### ISSUE THREAD

**Issue by UltramanSleepless** [ML4ITS/TimeVQVAE#5]

**Comment by danelee2601** [comment]
To clarify, the class-conditional learning process is conducted in the stage2 training.
[this line of the code](https://github.com/ML4ITS/TimeVQVAE/blob/515129242c00fd423ede7e7f63daa2cf86719849/generators/maskgit.py#L176) shows the part where the conditional information is fed into the prior model.
