### ISSUE TITLE
how can i use this model?

### ISSUE THREAD

**Issue by blht-chen** [ML4ITS/TimeVQVAE#6]
hi，I'm very interesting in your job,but i don't know how to use this model in my dataset,can you tell me some detail.Very thanks for your answer.

**Comment by Jimmy3141** [comment]
Hi, can you run this project right now?

**Comment by danelee2601** [comment]
I've recently added a feature for training the model on a custom dataset. See README.

**Comment by danelee2601** [comment]
and yes, it should run.
